service: pizzaria-project

frameworkVersion: '3'

provider:
    name: aws
    runtime: python3.8
    region: 'us-east-1'
    iam:
        role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
    eventBridge:
        useCloudFormation: true
        
functions:
    pedido:
        handler: handler.pedidoHandler
        events:
            - eventBridge:
                eventBus:
                    - arn:aws:events:${aws:region}:${aws:accountId}:event-bus/pizzaria
                pattern:
                    source:
                        - com.pizza.status
    enviarParaFila:
        handler: handler.enviarParaFilaHandler
        events:
            - eventBridge:
                eventBus:
                    - arn:aws:events:${aws:region}:${aws:accountId}:event-bus/pizzaria
                pattern:
                    detail-type:
                        - Alteracao Pizza
                    source:
                        - com.pizza.status
                    detail:
                        status:
                            - pronto
    entregue:
        handler: handler.entregueHandler
        events:
            - eventBridge:
                eventBus:
                    - arn:aws:events:${aws:region}:${aws:accountId}:event-bus/pizzaria
                pattern:
                    detail-type:
                        - Alteracao Pizza
                    source:
                        - com.pizza.status
                    detail:
                        status:
                            - pronto
